language: node_js
node_js:
- '4.3.1'
sudo: false
cache:
  directories:
  - node_modules
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database webmaker_oauth_test' -U postgres
deploy:
  - provider: heroku
    api_key:
      secure: cHZklHQUmzKbHcegrMPz/j+58mXjDVV2Xm5vTlvwoJyiEmzMg9ZT0U0PB2GJx/iHg+ubPKeKcoUBJavkw2PkgvwdLh5DvAIMyF5TDu2lIBVhLDPjzifkFLb59jUFMtJ5iYSSnilObf4QOqjNFXR8CXXC4YTC5/roE8k8fl+rWzs=
    app:
      develop: id-webmaker-org-staging
      master: id-webmaker-org-production
    on:
      repo: mozilla/id.webmaker.org
      node: '4.3.1'
  - provider: heroku
    api_key:
      secure: cHZklHQUmzKbHcegrMPz/j+58mXjDVV2Xm5vTlvwoJyiEmzMg9ZT0U0PB2GJx/iHg+ubPKeKcoUBJavkw2PkgvwdLh5DvAIMyF5TDu2lIBVhLDPjzifkFLb59jUFMtJ5iYSSnilObf4QOqjNFXR8CXXC4YTC5/roE8k8fl+rWzs=
    app:
      develop: id-webmaker-org-loadtesting
    on:
      repo: mozilla/id.webmaker.org
      node: '4.3.1'
